spring:
  application:
    name: Circuit-Breaker
    
management:
  endpoints.web.exposure.include:
    - '*'                         
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true


resilience4j.circuitbreaker:
  configs:
    default: # you can specify the name of circuit breaker if you want more than one
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 100s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      